### ISSUE TITLE
3d Buildings dont show

### ISSUE THREAD

**Issue by KalipheGTU** [philipbelesky/Caribou#17]
Hi great plugin
it's my first time working with thisplugin but i can't make buildings show up in canvas, and the progress bar in grasshopper stay stud at 99.06% 
when i add the buildings the data dont show u
![building](https://user-images.githubusercontent.com/19837071/143722620-fbb40b3f-3605-4dd8-82e2-7f7d4ef55353.jpg)
p

**Comment by philipbelesky** [comment]
Hi Kaliphe. Sorry to hear the buildings aren't showing up in this case. Could you attach the OSM file you are using? And, to confirm, are the Points/Lines components working properly?

**Comment by philipbelesky** [comment]
Also, I've just released a small update that hopefully addresses this issue. If you are game to test it (you can update in the Package Manager) that would be appreciated.

**Comment by KalipheGTU** [comment]
Hi
thank you for the answer the file is quite big

**Comment by KalipheGTU** [comment]
now it works fine than k you very much
have nice day and stay safe
